name: Nigthly
on:
#   schedule:
#     - cron: '* * * * *'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./ticket.sh "20210211,20210223,20210227,20210228,20210224,20210301,20210303,20210304,20210307"
      # - run: |
      #     ./restaurant.sh "20201129"
      # - run: |
      #     ./restaurant.sh "20201130" "(れすとらん北齋|ポリネシアンテラス・レストラン|レストラン櫻|ホライズンベイ・レストラン|シャーウッドガーデン・レストラン)"
