name: Nigthly
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./ticket.sh
      - run: |
          ./restaurant.sh "20201129"
      - run: |
          ./restaurant.sh "20201130"
      # "(れすとらん北齋|ポリネシアンテラス・レストラン|レストラン櫻|ホライズンベイ・レストラン)"
